version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr # https://github.com/linuxserver/docker-sonarr
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /Users/knarf/Movies/series:/tv
      - /Users/knarf/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission # https://hub.docker.com/r/linuxserver/transmission/
    container_name: transmission
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/London
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - /Users/knarf/Downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett # https://hub.docker.com/r/linuxserver/jackett/
    container_name: jackett
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/London
    volumes:
      - /Users/knarf/Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin # https://hub.docker.com/r/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/London
    volumes:
      - /Users/knarf/Movies/library:/config
      - /Users/knarf/Movies/series:/data/tvshows
      - /Users/knarf/Movies/movies:/data/movies
      #- /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped
