version: "2.1"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - traefik
      - default

  dave:
    container_name: dave
    image: theknarf/dave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.dave.rule=Host(`localhost`) || Host(`${DOCKER_HOSTNAME}`) || Host(`${DOCKER_DOMAINNAME}`)"
      - "traefik.dashboard.port=80"
    restart: unless-stopped
    networks:
      - traefik
      - default

  caddy:
    container_name: caddy
    build:
      context: ./caddy/
      args:
        - DIGITALOCEAN_API_TOKEN=${DIGITALOCEAN_API_TOKEN}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}:/config
      - ${DOCKER_DATA_FOLDER}:/data
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - traefik
      - default

networks:
  traefik:
    name: traefik_network
