version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${MEDIA_LOCATION}/prometheus:/etc/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`) || Host(`prometheus.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=prometheus"
    restart: unless-stopped
    profiles:
      - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`) || Host(`grafana.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=grafana"
    restart: unless-stopped
    profiles:
      - prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
#    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
    profiles:
      - prometheus
