version: "3.5"
services:
  sonarr:
    image: linuxserver/sonarr # https://github.com/linuxserver/docker-sonarr
    container_name: sonarr
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/sonarr:/config
      - ${DOCKER_TV_SERIES_FOLDER}:/tv
      - ${DOCKER_DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`) || Host(`sonarr.${DOCKER_DOMAINNAME}`)"
      - "traefik.sonarr.port=8989"
      - "dave.relativeSubdomain=sonarr"
    networks:
      - traefik
      - default

  transmission:
    image: linuxserver/transmission # https://hub.docker.com/r/linuxserver/transmission/
    container_name: transmission
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
      - USER=${DOCKER_TORRENT_USERNAME}
      - PASS=${DOCKER_TORRENT_PASSWORD}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/transmission:/config
      - ${DOCKER_DOWNLOADS_FOLDER}:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.transmission.rule=Host(`transmission.localhost`) || Host(`transmission.${DOCKER_DOMAINNAME}`)"
      - "traefik.transmission.port=9091"
      - "dave.relativeSubdomain=transmission"
    networks:
      - traefik
      - default

  jackett:
    image: linuxserver/jackett # https://hub.docker.com/r/linuxserver/jackett/
    container_name: jackett
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/jackett:/config
      - ${DOCKER_DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.jackett.rule=Host(`jackett.localhost`) || Host(`jackett.${DOCKER_DOMAINNAME}`)"
      - "traefik.jackett.port=9117"
      - "dave.relativeSubdomain=jackett"
    networks:
      - traefik
      - default

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:arm32v7-latest # https://hub.docker.com/r/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/jellyfin:/config
      - ${DOCKER_TV_SERIES_FOLDER}:/data/tvshows
      - ${DOCKER_MOVIES_FOLDER}:/data/movies
      - ${DOCKER_YOUTUBE_DOWNLOADS_FOLDER}:/data/youtube
#      - /opt/vc/lib:/opt/vc/lib #optional
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.localhost`) || Host(`jellyfin.${DOCKER_DOMAINNAME}`)"
      - "traefik.jellyfin.port=8096"
      - "dave.relativeSubdomain=jellyfin"
      - "dave.icon=simple-icons:jellyfin"
    restart: unless-stopped
    networks:
      - traefik
      - default

  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    ports:
      - "8081:8081"
    volumes:
      - ${DOCKER_YOUTUBE_DOWNLOADS_FOLDER}:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.metube.rule=Host(`metube.localhost`) || Host(`metube.${DOCKER_DOMAINNAME}`)"
      - "traefik.metube.port=8081"
      - "dave.relativeSubdomain=metube"
      - "dave.icon=mdi-youtube"
    networks:
      - traefik
      - default

networks:
  traefik:
    external:
      name: traefik_network
