version: "2.1"
services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  dashboard:
    container_name: sui
    build:
      context: ./dashboard/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${DOCKER_HOSTNAME}`) || Host(`${DOCKER_DOMAINNAME}`)"
      - "traefik.dashboard.port=80"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr # https://github.com/linuxserver/docker-sonarr
    container_name: sonarr
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/sonarr:/config
      - ${DOCKER_TV_SERIES_FOLDER}:/tv
      - ${DOCKER_DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOCKER_DOMAINNAME}`)"
      - "traefik.sonarr.port=8989"
  transmission:
    image: linuxserver/transmission # https://hub.docker.com/r/linuxserver/transmission/
    container_name: transmission
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
      - USER=${DOCKER_TORRENT_USERNAME}
      - PASS=${DOCKER_TORRENT_PASSWORD}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/transmission:/config
      - ${DOCKER_DOWNLOADS_FOLDER}:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.${DOCKER_DOMAINNAME}`)"
      - "traefik.transmission.port=9091"
  jackett:
    image: linuxserver/jackett # https://hub.docker.com/r/linuxserver/jackett/
    container_name: jackett
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/jackett:/config
      - ${DOCKER_DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOCKER_DOMAINNAME}`)"
      - "traefik.jackett.port=9117"
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:arm32v7-latest # https://hub.docker.com/r/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
      - JELLYFIN_PublishedServerUrl=192.168.1.170
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/jellyfin:/config
      - ${DOCKER_TV_SERIES_FOLDER}:/data/tvshows
      - ${DOCKER_MOVIES_FOLDER}:/data/movies
#      - /opt/vc/lib:/opt/vc/lib #optional
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOCKER_DOMAINNAME}`)"
      - "traefik.jellyfin.port=8096"
    restart: unless-stopped
