version: "3.5"

volumes:
  db:
  redis:

services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/komga:/config
      - ${DOCKER_COMIC_FOLDER}:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.komga.rule=Host(`konga.localhost`) || Host(`komga.${DOCKER_DOMAINNAME}`)"
      - "traefik.komga.port=25600"
      - "dave.relativeSubdomain=komga"
      - "dave.icon=arcticons:comicscreen"
    restart: unless-stopped
    networks:
      - traefik
      - default

  kaizoku:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@kaizokudb:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=kaizokuredis
      - REDIS_PORT=6379
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${DOCKER_COMIC_FOLDER}:/data
      - ${DOCKER_COMIC_FOLDER}/kaizoku:/config
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      kaizokudb:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.kaizoku.rule=Host(`kaizoku.localhost`) || Host(`kaizoku.${DOCKER_DOMAINNAME}`)"
      - "traefik.komga.port=3000"
      - "dave.relativeSubdomain=kaizoku"
      - "dave.icon=arcticons:manga-up"

  kaizokuredis:
    image: redis:7-alpine
    volumes:
      - redis:/data

  kaizokudb:
    container_name: kaizokudb
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - db:/var/lib/postgresql/data

networks:
  traefik:
    external:
      name: traefik_network
