version: "3.5"

volumes:
  db:
  redis:

services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/komga:/config
      - ${DOCKER_COMIC_FOLDER}:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.komga.rule=Host(`konga.localhost`) || Host(`komga.${DOCKER_DOMAINNAME}`)"
      - "traefik.komga.port=25600"
      - "dave.relativeSubdomain=komga"
      - "dave.icon=arcticons:comicscreen"
    restart: unless-stopped
    networks:
      - traefik
      - default

networks:
  traefik:
    external:
      name: traefik_network
