version: "2.1"
services:
  samba:
    container_name: samba
    build:
      context: ./rpi-samba/
    volumes:
      - /media/ssd:/shared/ssd
    ports:
      - 445:445
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TIMEZONE}
      - SAMBA_PASSWORD=${DOCKER_SAMBA_PASSWORD}
