services:
  sonarr:
    image: linuxserver/sonarr # https://github.com/linuxserver/docker-sonarr
    container_name: sonarr
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK_SET=022 #optional
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/sonarr:/config
      - ${MEDIA_LOCATION}/tv:/tv
      - ${MEDIA_LOCATION}/downloads:/downloads
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`) || Host(`sonarr.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=sonarr"
    restart: unless-stopped
    profiles:
      - multimedia

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/radarr:/config
      - ${MEDIA_LOCATION}/movies:/movies
      - ${MEDIA_LOCATION}/downloads:/downloads
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.localhost`) || Host(`radarr.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=radarr"
    restart: unless-stopped
    profiles:
      - multimedia

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/bazarr:/config
      - ${MEDIA_LOCATION}/movies:/movies
      - ${MEDIA_LOCATION}/tv:/tv
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.localhost`) || Host(`bazarr.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=bazarr"
    restart: unless-stopped
    profiles:
      - multimedia

  transmission:
    image: linuxserver/transmission # https://hub.docker.com/r/linuxserver/transmission/
    container_name: transmission
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - USER=${USER}
      - PASS=${DOCKER_TORRENT_PASSWORD}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/transmission:/config
      - ${MEDIA_LOCATION}/downloads:/downloads
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 51413:51413
      - 51413:51413/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.localhost`) || Host(`transmission.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=transmission"
    restart: unless-stopped
    profiles:
      - multimedia

  jackett:
    image: linuxserver/jackett # https://hub.docker.com/r/linuxserver/jackett/
    container_name: jackett
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/jackett:/config
      - ${MEDIA_LOCATION}/downloads:/downloads
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.localhost`) || Host(`jackett.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=jackett"
    restart: unless-stopped
    profiles:
      - multimedia

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin # https://hub.docker.com/r/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${DOCKER_CONFIG_FOLDER}/jellyfin:/config
      - ${MEDIA_LOCATION}/tv:/data/tvshows
      - ${MEDIA_LOCATION}/movies:/data/movies
      - ${MEDIA_LOCATION}/youtube:/data/youtube
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #- /opt/vc/lib:/opt/vc/lib #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.localhost`) || Host(`jellyfin.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=jellyfin"
      - "dave.icon=simple-icons:jellyfin"
    restart: unless-stopped
    profiles:
      - multimedia

  metube:
    image: alexta69/metube
    container_name: metube
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    volumes:
      - ${MEDIA_LOCATION}/youtube:/downloads
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube.rule=Host(`metube.localhost`) || Host(`metube.${DOCKER_DOMAINNAME}`)"
      - "dave.relativeSubdomain=metube"
      - "dave.icon=mdi-youtube"
    restart: unless-stopped
    profiles:
      - multimedia
